defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password:
  host: localhost
  port: 5432

development:
  <<: *defaults
  database: shafa_development

test:
  <<: *defaults
  database: shafa_test

production:
  <<: *defaults
  database: shafa_test_production

